app/routes/gpt.py
from flask import Blueprint, abort, current_app, jsonify, redirect, render_template, request, send_from_directory, url_for
from flask_login import current_user, login_required
from ..functions import get_all_gpts, gpt_send_message, save_picture, generate_img, create_chat, add_to_chat, compress_base64
from ..extensions import client, db
from ..models.user import User, Chats, Messages
from sqlalchemy import desc
from werkzeug.utils import secure_filename
import markdown

gpt = Blueprint('gpt', __name__)

@gpt.route('/gpt', methods = ['POST', 'GET'])
def gpt_page():
    gpts = get_all_gpts()
    if current_user.is_authenticated:
        choice_elements = Chats.query.filter_by(user_id = current_user.id).order_by(desc(Chats.date)).all()
        return render_template('gpt/gpt_page.html',gpts=gpts, choice_elements = choice_elements)
    else:
        return render_template('gpt/gpt_page.html',gpts=gpts)

    

@gpt.route("/gpt/<uuid:chat_id>", methods=["GET"])
@login_required
def chat(chat_id):
    if str(current_user.id) == Chats.query.filter_by(id = str(chat_id)).first().user_id:
        gpts = get_all_gpts()
        choice_elements = Chats.query.filter_by(user_id = current_user.id).order_by(desc(Chats.date)).all()
        model = Chats.query.filter_by(id = str(chat_id)).first().model

        messages = Messages.query.filter_by(chat_id = str(chat_id)).all()
        for message in messages:
            if message.message:
                message.message = markdown.markdown(message.message, extensions=['fenced_code'])


        return render_template('gpt/gpt_page.html',gpts=gpts, choice_elements = choice_elements, model=model, messages=messages)
    
    else:
        abort(403)

@gpt.route("/gpt/<uuid:chat_id>/delete", methods=["GET"])
@login_required
def delete_chat(chat_id):
    if str(current_user.id) == Chats.query.filter_by(id = str(chat_id)).first().user_id:
        remove_chat = Chats.query.filter_by(id = str(chat_id)).first()
        db.session.delete(remove_chat)
        db.session.commit()


        return redirect("/gpt")
    
    else:
        abort(403)
    

@gpt.route('/uploads/temp/<filename>', methods=['GET'])
def get_uploaded_temp(filename):
    """Возвращает загруженное временное фото по его имени"""
    return send_from_directory(current_app.config['UPLOAD_TEMP_PATH'], filename)

@gpt.route('/uploads/<filename>', methods=['GET'])
@login_required
def get_uploaded_private(filename):
    """Возвращает загруженное приватное фото по его имени"""
    if current_user.id == Messages.query.filter_by(media = filename).first().user_id:
        return send_from_directory(current_app.config['UPLOAD_PATH'], filename)
    abort(403)


@gpt.route("/send", methods=["POST"])
def send():
    try:
        # general info
        model = request.form.get("gpt") #'gpt'
        generate_img_mode = request.form.get("generate_img_mode") #'true'/'false'
        database_mode = request.form.get("database_mode") #'guest/create_chat/add_to_chat'
        chat_id = request.form.get("chat_id") #'chat_id'

        #messages
        user_message = request.form.get("user_message") #'text'
        photo = request.files.get("photo") #'bytes'

        #user_info (protected)
        authenticated = current_user.is_authenticated
        user_id = current_user.id if authenticated else None

        photo_base64 = None
        bot_url = None
        message = None
        chat_url = None
        photo_path = None
        bot_photo_path = None
        #Данные________________________________________________________________________________________________
        if photo != None and photo.filename.rsplit('.',1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS_PHOTOS']: #вопрос с фото или без
            photo_base64 = compress_base64(photo.read()) #base64 -> compressed base64

        if generate_img_mode == 'true': #генерация фото
                bot_url = generate_img(user_message, model) #base64
        else:
            message = gpt_send_message(user_message, model, photo_base64=photo_base64)

        if authenticated:
            if bot_url:
                bot_photo_path = save_picture(bot_url, temp=False, img_type='base64')
            if photo_base64:
                photo_path = save_picture(photo_base64, temp=False, img_type='base64')
            match database_mode:
                case 'create_chat':
                    chat_url = create_chat(user_id=user_id, model=model, user_message=user_message, photo_path=photo_path, message=message, bot_photo_path=bot_photo_path)
                case 'add_to_chat':
                    add_to_chat(chat_id=chat_id, user_id=user_id, model=model, user_message=user_message, photo_path=photo_path, message=message, bot_photo_path=bot_photo_path)
                case _:
                    pass
                

        return jsonify({
            "status": "success",
            "message": markdown.markdown(message, extensions=['fenced_code']),
            "bot_url": bot_url,
            "redirection": chat_url
        }), 200
        

    except Exception as e:
        current_app.logger.error(f"Ошибка обработки сообщения: {str(e)}", exc_info=True)

        return jsonify({
            "status": "error",
            "message": 'Server Error'
        }), 500

app/routes/storage.py
from flask import Blueprint, redirect, render_template, flash, request, url_for
from flask_login import login_user, logout_user
from ..extensions import db, bcrypt
from ..models.user import User
from ..forms import RegistrationForm, LoginForm
from ..functions import save_picture

storage = Blueprint('storage', __name__)

@storage.route('/storage', methods = ['POST', 'GET'])
def storage_page():
    return 'In devolopment', 200

app/routes/user.py
from flask import Blueprint, redirect, render_template, flash, request, url_for
from flask_login import login_user, logout_user
from ..extensions import db, bcrypt
from ..models.user import User
from ..forms import RegistrationForm, LoginForm
from ..functions import save_avatar_picture

user = Blueprint('user', __name__)

@user.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_avatar_picture(form.avatar.data)
        user = User(username = form.username.data, avatar = avatar_filename, password = hashed_password)

        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Registration Successfull", "success")
            return redirect(url_for('user.login'))
        except Exception as err:
            print(err)
            flash(f"Registration Error", "danger")  
    return render_template('user/register.html', form=form) 

@user.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')

            flash(f"Welcome, {user.username}!", "success")
            return redirect(next_page) if next_page else redirect(url_for('index.index_page'))
        else:
            flash(f"Error", "danger")
    return render_template('user/login.html', form=form) 
        
@user.route('/user/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('index.index_page'))

app/templates/main/_flash.html
<!-- FLASH MEssages -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="flash-container">
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} fade show flash-message" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}
<!-- FLASH MEssages -->

app/templates/main/_header.html
<a href="{{ url_for('index.index_page') }}" class="index-link h1">Blessed</a>
<nav class="h2">
      <a href="{{ url_for('gpt.gpt_page') }}">GPT</a>
      <a href="{{ url_for('storage.storage_page') }}">Storage</a>
      {% if current_user.is_authenticated %}
            <div class="user-header-element">
                  {% if current_user.avatar %}
                        <img src="{{ url_for('static', filename='uploads/'~ current_user.avatar) }}" alt="user_avatar" class="user_avatar">
                  {% else %}
                        <img src="{{ url_for('static', filename='media/default-avatar.png') }}" alt="user_avatar" class="user_avatar">
                  {% endif %}
                  <span class="user_nickname">{{ current_user.username }}</span>
                  <a href="{{ url_for('user.logout') }}"><i class="bi bi-box-arrow-right"></i></a>
            </div>
      {% else %}
            <a href="{{ url_for('user.login') }}" class="login-btn h2">Login</a>
      {% endif %}
</nav>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="{{ url_for('static', filename='media/favicon.ico') }}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap-icons-1.11.3/font/bootstrap-icons.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="keywords" content="{% block keywords %}{% endblock %}">
        <meta name="yandex-verification" content="5eae949f28eb34f2" />
    </head>
    <body>
        <header>{% include 'main/_header.html' %}</header>
        <main class="content">
            {% include 'main/_flash.html' %}
            {% block content %}{% endblock %}
        </main>
        <footer>{% include 'main/_footer.html' %}</footer>

        <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/base.js') }}"></script>
        {% block script %}{% endblock %}
    </body>
</html>

app/templates/main/index.html
{% extends "main/base.html" %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/scene.css') }}">
{% endblock %}

{% block title %}
Info page
{% endblock %}

{% block description %}
Welcome to main page of my diverse purpose website😊
{% endblock %}

{% block keywords %}
Blessed, Blessed website, GPT, ChatGPT, Gemini, Ai, Temp Storage, Project
{% endblock %}

{% block content %}
<div class="scene">
    <div class="cube">
        <div class="face front"></div>
        <div class="face back"></div>
        <div class="face left"></div>
        <div class="face right"></div>
        <div class="face top"></div>
        <div class="face bottom"></div>
    </div>
    <div class="fixed-text">
        <p>Made by Liexer</p>
        <br>
        <br>
        <a href="https://github.com/Radma123" class="btn">Github</a>
        <a href="https://x.com/Liexerrr1232" class="btn">Twitter</a>

    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}