app/models/user.py
import uuid
from datetime import datetime, timezone
from ..extensions import db, login_manager
from flask_login import UserMixin
import os
from flask import current_app

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = 'user'
    
    id = db.Column(db.String, primary_key=True, default=lambda: str(uuid.uuid4()))
    status = db.Column(db.String(50), nullable=False, default='user')

    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)
    avatar = db.Column(db.String(250))

    date = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    @staticmethod
    def before_delete(mapper, connection, target):
        """Обработчик событий для удаления пользователя."""
        print(f"Удаление пользователя с ID: {target.id}")
        # Получаем все чаты, связанные с этим пользователем, и удаляем файлы сообщений
        chats = Chats.query.filter_by(user_id=target.id).all()
        for chat in chats:
            # Для каждого чата удаляем связанные с ним сообщения
            messages = Messages.query.filter_by(chat_id=chat.id).all()
            for message in messages:
                message.delete_file()  # Удаление файла из сообщений
            # Чат будет удалён каскадно, так что можем обработать файлы сообщений до его удаления
            db.session.delete(chat)


class Chats(db.Model):
    __tablename__ = 'chats'
    
    id = db.Column(db.String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = db.Column(db.String, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    model = db.Column(db.String(50), nullable=False)
    first_message = db.Column(db.String(100))

    date = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    @staticmethod
    def before_delete(mapper, connection, target):
        """Обработчик событий для удаления чатов."""
        print(f"Удаление чата с ID: {target.id}")
        # Получаем все сообщения, связанные с этим чатом, и удаляем файлы
        messages = Messages.query.filter_by(chat_id=target.id).all()
        for message in messages:
            message.delete_file()


class Messages(db.Model):
    __tablename__ = 'messages'
    
    id = db.Column(db.String, primary_key=True, default=lambda: str(uuid.uuid4()))
    chat_id = db.Column(db.String, db.ForeignKey('chats.id', ondelete='CASCADE'), nullable=False)
    user_id = db.Column(db.String, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    sender = db.Column(db.String(40), nullable=False)
    message = db.Column(db.Text)
    media = db.Column(db.String(200))

    date = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def delete_file(self):
        """Удаляет файл с диска перед удалением записи из БД."""
        if self.media is None:
            return
        
        file_path = os.path.join(current_app.config['UPLOAD_PATH'], self.media)
        print(f"Пытаемся удалить файл: {file_path}")
        if os.path.exists(file_path):
            os.remove(file_path)
            print("Файл удалён")
        else:
            print(f"Файл не найден: {file_path}")

app/routes/user.py
from flask import Blueprint, redirect, render_template, flash, request, url_for
from flask_login import login_user, logout_user
from ..extensions import db, bcrypt
from ..models.user import User
from ..forms import RegistrationForm, LoginForm
from ..functions import save_avatar_picture

user = Blueprint('user', __name__)

@user.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_avatar_picture(form.avatar.data)
        user = User(username = form.username.data, avatar = avatar_filename, password = hashed_password)

        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Registration Successfull", "success")
            return redirect(url_for('user.login'))
        except Exception as err:
            print(err)
            flash(f"Registration Error", "danger")  
    return render_template('user/register.html', form=form) 

@user.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')

            flash(f"Welcome, {user.username}!", "success")
            return redirect(next_page) if next_page else redirect(url_for('index.index_page'))
        else:
            flash(f"Error", "danger")
    return render_template('user/login.html', form=form) 
        
@user.route('/user/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('index.index_page'))

app/templates/user/login.html
{% extends "main/base.html" %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
{% endblock %}

{% block title %}Авторизация{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center login-form">
    <div class="card shadow-lg p-4 rounded-4" style="width: 350px;">
        <h2 class="text-center mb-3">Login</h2>
        <form method="post">
            {{ form.csrf_token }}

            <div class="mb-3">
                {{ form.username(class='form-control', placeholder='Username') }}
            </div>
            <div class="mb-3">
                {{ form.password(class='form-control', placeholder='Password') }}
            </div>

            <div class="form-check d-flex align-items-center gap-2 mb-3">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>

            <button type="submit" class="btn btn-success w-100 btn-hover">Enter</button>
        </form>
    </div>
    <div class="card shadow-lg p-4 rounded-4" style="width: 350px;">
        <a href="{{ url_for('user.register') }}" class="btn btn-warning w-100 btn-hover">Register</a>
    </div>
</div>
{% endblock %}

app/templates/user/register.html
{% extends "main/base.html" %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
{% endblock %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center register-form">
    <div class="card shadow-lg p-4 rounded-3" style="max-width: 400px; width: 100%;">
        <h2 class="text-center mb-4">Registration</h2>
        
        <form method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}

            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control" ~ (' is-invalid' if form.username.errors else '')) }}
                {% for error in form.username.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.avatar.label(class="form-label") }}
                {{ form.avatar(class="form-control" ~ (' is-invalid' if form.avatar.errors else '')) }}
                {% for error in form.avatar.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control" ~ (' is-invalid' if form.password.errors else '')) }}
                {% for error in form.password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password(class="form-control" ~ (' is-invalid' if form.confirm_password.errors else '')) }}
                {% for error in form.confirm_password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-warning w-100 btn-hover">Register</button>
        </form>
    </div>
</div>
{% endblock %}